### ISSUE TITLE
anuga import error

### ISSUE THREAD

**Issue by dunkgray** [GeoscienceAustralia/glue_hazimp#2]
Getting this when running on rhe-compute1;
/nas/mnh/georisk_models/hazard_impact/sandpits$ python quick.py 
Traceback (most recent call last):
  File "quick.py", line 1, in <module>
    from anuga.file_conversion.sww2dem import sww2dem
  File "/nas/mnh/georisk_models/inundation/sandpits/dgray/anuga_core/anuga/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: Error importing anuga: you should not try to import anuga from
        its source directory; please exit the anuga source tree, and relaunch
        your python interpreter from there.

**Comment by dunkgray** [comment]
This is an issue with anuga
