### ISSUE TITLE
Port Hedland example crashing 

### ISSUE THREAD

**Issue by dunkgray** [GeoscienceAustralia/glue_hazimp#3]
@rhe-compute1:/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/glue_hazimp/tcrm$ python go.py
Pypar (version 2.1.5) initialised MPI OK with 1 processors
ini_file /nas/mnh/georisk_models/hazard_impact/sandpits/duncan/glue_hazimp/tcrm/port_hedland.ini
ERROR 4: `/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/glue_hazimp/tcrm/output/port_hedland/windfield/gust-0000.txt' does not exist in the file system,
and is not recognised as a supported dataset name.

Traceback (most recent call last):
  File "go.py", line 54, in <module>
    hazimp.start(config_list=config)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/hazimp.py", line 52, in start
    the_pipeline.run(cont_in)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/pipeline.py", line 69, in run
    job(context)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/workflow.py", line 54, in __call__
    self.job_instance(*args, **job_kwargs)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/jobs/jobs.py", line 570, in __call__
    context.exposure_lat, file_list)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/raster.py", line 202, in files_raster_data_at_points
    a_raster = Raster.from_file(filename)
  File "/nas/mnh/georisk_models/hazard_impact/sandpits/duncan/github_hazimp/core_hazimp/raster.py", line 81, in from_file
    raise RuntimeError('Invalid file: %s' % filename)
RuntimeError: Invalid file: /nas/mnh/georisk_models/hazard_impact/sandpits/duncan/glue_hazimp/tcrm/output/port_hedland/windfield/gust-0000.txt

**Comment by dunkgray** [comment]
../../tcrm/Utilities/nc2txt.py is silently not producing results.
Let's skip that step then.
